CREATE USER 'poseidontestusr'@'localhost' IDENTIFIED BY 'test';
GRANT Usage ON *.* TO 'poseidontestusr'@'localhost';
GRANT Alter ON poseidontest.* TO 'poseidontestusr'@'localhost';
GRANT Create ON poseidontest.* TO 'poseidontestusr'@'localhost';
GRANT Create view ON poseidontest.* TO 'poseidontestusr'@'localhost';
GRANT Delete ON poseidontest.* TO 'poseidontestusr'@'localhost';
GRANT Drop ON poseidontest.* TO 'poseidontestusr'@'localhost';
GRANT Grant option ON poseidontest.* TO 'poseidontestusr'@'localhost';
GRANT Index ON poseidontest.* TO 'poseidontestusr'@'localhost';
GRANT Insert ON poseidontest.* TO 'poseidontestusr'@'localhost';
GRANT References ON poseidontest.* TO 'poseidontestusr'@'localhost';
GRANT Select ON poseidontest.* TO 'poseidontestusr'@'localhost';
GRANT Show view ON poseidontest.* TO 'poseidontestusr'@'localhost';
GRANT Trigger ON poseidontest.* TO 'poseidontestusr'@'localhost';
GRANT Update ON poseidontest.* TO 'poseidontestusr'@'localhost';
GRANT Alter routine ON poseidontest.* TO 'poseidontestusr'@'localhost';
GRANT Create routine ON poseidontest.* TO 'poseidontestusr'@'localhost';
GRANT Create temporary tables ON poseidontest.* TO 'poseidontestusr'@'localhost';
GRANT Execute ON poseidontest.* TO 'poseidontestusr'@'localhost';
GRANT Lock tables ON poseidontest.* TO 'poseidontestusr'@'localhost';
GRANT Grant option ON poseidontest.* TO 'poseidontestusr'@'localhost';
